// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentCapabilityBinding = { capabilityId: string, autoCreate?: boolean, };

export type AgentFilesystem = { readPaths?: Array<string>, writePaths?: Array<string>, };

export type AgentInheritFrom = { name: string, overrides: Array<string>, };

export type AgentKindTag = "Agent";

/**
 * Top-level Agent manifest object.
 *
 * Note: `kind` is hard-coded to `"Agent"` via `tag = "kind"` on `AnyManifest`,
 * but here in the standalone struct we still serialize it explicitly so a
 * stand-alone `agent.yaml` round-trips faithfully.
 */
export type AgentManifest = { apiVersion: string, kind: AgentKindTag, metadata: Metadata, spec: AgentSpec, };

/**
 * Discriminator for agent execution mode.
 */
export type AgentMode = "primary" | "subagent";

export type AgentModelConfig = { provider: string, modelID: string, temperature?: number, maxTokens?: number, topP?: number, };

export type AgentNetwork = { allowedHosts: Array<string>, };

export type AgentResources = { maxTokensPerSession?: number, maxToolCallsPerMinute?: number, maxConcurrentSessions?: number, };

export type AgentSpec = { mode: AgentMode, basePrompt: string, contextTemplate?: string, contextKeys?: Array<string>, skills?: Array<string>, inheritFrom?: AgentInheritFrom, tools: AgentTools, permission?: Array<PermissionRule>, model?: AgentModelConfig, resources?: AgentResources, network?: AgentNetwork, filesystem?: AgentFilesystem, capabilityBinding?: AgentCapabilityBinding, };

export type AgentTools = { allowed: Array<string>, deny?: Array<string>, autoApprove?: Array<string>, };

/**
 * Discriminated union — useful for callers that don't yet know the kind.
 */
export type AnyManifest = { "kind": "Agent" } & AgentManifest | { "kind": "Skill" } & SkillManifest | { "kind": "Capability" } & CapabilityManifest;

/**
 * HR-domain category enumeration.
 *
 * Keep parity with `manifestSchema.ts`'s `CapabilityCategory` literal union.
 */
export type CapabilityCategory = "hr-screening" | "hr-jd" | "hr-interview" | "hr-report" | "hr-internal" | "productivity" | "entertainment" | "system" | "custom";

export type CapabilityInputField = { key: string, label: string, type: string, 
/**
 * `default` is `unknown` in TS — we keep it as serde_json::Value for parity.
 */
default?: unknown, options?: Array<string>, };

export type CapabilityKindTag = "Capability";

export type CapabilityManifest = { apiVersion: string, kind: CapabilityKindTag, metadata: Metadata, spec: CapabilitySpec, };

export type CapabilitySpec = { agentName: string, category: CapabilityCategory, order?: number, badge?: string, color?: string, contextKeys: Array<string>, entryPrompt?: string, quickReplies?: Array<string>, inputSchema?: Array<CapabilityInputField>, visibility?: CapabilityVisibility, };

export type CapabilityVisibility = { enabled?: boolean, requiredFeatureFlags?: Array<string>, requiredRoles?: Array<string>, };

/**
 * Shared metadata across all three manifest kinds.
 */
export type Metadata = { name: string, displayName: string, description: string, source: Source, version: string, author: string | null, authorEmail?: string, icon: string | null, tags: Array<string> | null, createdAt: string, updatedAt?: string, deprecated: boolean | null, deprecatedReason?: string, homepage: string | null, signature: string | null, };

export type PermissionAction = "allow" | "deny" | "ask";

/**
 * Permission rule — shared by Agent and certain Skills.
 */
export type PermissionRule = { permission: string, pattern: string, action: PermissionAction, };

export type SkillInput = { key: string, type: string, required?: boolean, };

export type SkillKindTag = "Skill";

export type SkillLoadStrategy = "eager" | "lazy";

export type SkillManifest = { apiVersion: string, kind: SkillKindTag, metadata: Metadata, spec: SkillSpec, 
/**
 * SKILL.md body (Markdown). Optional — sidecar `.SKILL.md` file overrides.
 */
body?: string, };

export type SkillOutputs = { schema?: string, };

export type SkillSpec = { applicableAgents?: Array<string>, applicableCapabilities?: Array<string>, requiredTools: Array<string>, requiredSkills?: Array<string>, resources?: Array<string>, inputs?: Array<SkillInput>, outputs?: SkillOutputs, loadStrategy?: SkillLoadStrategy, triggerKeywords?: Array<string>, };

/**
 * Source of a manifest — controls sandbox fast-path and tool whitelist.
 */
export type Source = "builtin" | "user" | "marketplace";
